### ISSUE TITLE
How to disable time out

### ISSUE THREAD

**Issue by poomzatanz** [thomasdondorf/puppeteer-cluster#166]
const cluster = await Cluster.launch({
    monitor: true,
    maxConcurr้ency: 2,
    timeout: 0,// **Here I want to disable it**
    puppeteerOptions: {
        headless: false,
        ignoreHTTPSErrors: true,
    },
  });

**Comment by maeroso** [comment]
I have this doubt too. How the cluster timeout relates to puppeteerOptions timeout? Are they the same thing? If I disable puppeteerOptions timeout, the cluster timeout would finish the task even so?

**Comment by thomasdondorf** [comment]
The `timeout` in `options` is for the full task. Your task will not be aborted but still continue to run (as Promises cannot be aborted..) in the background. If you want to disable the `timeout` for functions like `page.goto`, you have to still set it when calling them.

Hope that makes it more clear :)

**Comment by Zebiano** [comment]
Forgive me for asking here instead of Stack Overflow, but I felt like using an already existing issue is better than creating a new one with the same topic.

I'd love to be able to set `timeout: 0` to completely disable it, as when running more than 3/5 `concurrency`, most of the tasks get a timeout by surpassing 30 seconds. I guess I don't have hardware good enough to run more concurrencies, but I'd like to run some tests without the timeout. I know it's also possible to put a stupidly high timeout, but I don't like that approach, and prefer to completely disable it.

Your answer did not really answer the Issue/Question: How is it possible to disable timeout completely? Is it even possible? Would it make sense to even have the feature?

**Comment by thomasdondorf** [comment]
Currently, it's not possible to completely disable the timeout as you want to. So best way is, to set it to `Number.MAX_SAFE_INTEGER` or even infinity.

> Would it make sense to even have the feature?

Sure, makes sense to me . I think it makes sense to just disable it in case it's set to `0`. Interested in submitting a pull request? :)

**Comment by Zebiano** [comment]
Good to know then. I might think about it!
